'''
Task 9

Sebastian Montoya Hernandez

Generate a random 2D path that adds steps, and the length of each step follows the exponential distribution exp(-x/lambda)/lambda.

Lambda is an arbitrary constant.

x = -lambda * log(1 - r)
r generated by random.random()
'''
# Grade: 5.0

import random
from visual.graph import *
escena = display(width=500, height=500, range=20)

N = 20
lamb = 3
grafico = curve(x=list(range(0, N)), color=color.green)
xx = []
yy = []

def distnormal(N):
    for i in range(0, N):
        r1 = random.random()
        r2 = random.random()
        x = -lamb * log(1 - r1)
        y = -lamb * log(1 - r2)
        xx.append(x)
        yy.append(y)

distnormal(N)
for i in range(0, N):
    grafico.x[i] = xx[i]
    grafico.y[i] = yy[i]
    rate(5)
